data <- read.table('household_power_consumption.txt', header=TRUE, na.strings = '?', sep = ';')
data1 <- subset(data, (Date == '1/2/2007') | (Date == '2/2/2007'))
hist(data1$Global_active_power, col='red', xlab='Global Active Power (kilowatts)', ylab='Frequency', main='Global Active power')
dev.copy(png, file = 'plot1.png', width=480, height=480)
dev.off()
