data <- read.table('household_power_consumption.txt', header=TRUE, na.strings = '?', sep = ';')
data1 <- subset(data, (Date == '1/2/2007') | (Date == '2/2/2007'))
data1$x <- paste(data1$Date, data1$Time, sep=' ')
data1$x <- strptime(data1$x, '%d/%m/%Y %H:%M:%S')
png(file="plot3.png",width=480,height=480, units = 'px')
plot(data1$x, data1$Sub_metering_1, type = 'n', ylab = 'Energy sub meeting', xlab = '')
lines(data1$x, data1$Sub_metering_1, type = 'l')
lines(data1$x, data1$Sub_metering_2, type = 'l', col = 'red')
lines(data1$x, data1$Sub_metering_3, type = 'l', col = 'blue')
legend("topright", pch = '_', col = c("black", "red", 'blue'), legend = c("Sub_metering_1", "Sub_metering_2", 'Sub_metering_3'))
dev.off()